name: Daily Update

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}  # Use a Personal Access Token if needed

      - name: Run Update Script
        run: |
          echo "Daily repository update at $(date)" > daily_update.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name "ianC10"  # Replace with your actual GitHub username
          git config --global user.email "23f3001752@ds.study.iitm.ac.in"  # Replace with your email
          git add daily_update.txt
          git commit -m "Daily automated repository update"
          git push origin main
