name: Daily Repository Update

on:
  schedule:
    - cron: '17 14 * * *'  # Runs at 2:17 PM UTC daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-repo:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}
    
    - name: Set up Git
      run: |
        git config --global user.name 'DevSync Automation'
        git config --global user.email '23f3001752@ds.study.iitm.ac.in'
    
    - name: Create Daily Update
      run: |
        echo "Daily repository update at $(date)" > daily_update.txt
        git add daily_update.txt
        git commit -m "Daily automated repository update"
        git push
